using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtmView.Entities

{
	[Table("ONLINE_AUTHORIZATION")]

	public class ONLINE_AUTHORIZATION
	{
		[Key]
		public decimal AUT_CODE { get; set; }
		public string AUT_EXTE_CODE { get; set; }
		public int? AUT_SOUR_INTE_CODE { get; set; }
		public string AUT_PROC_INTE_CODE { get; set; }
		public int? AUT_DEST_INTE_CODE { get; set; }
		public int? AUT_AUTH_INTE_CODE { get; set; }
		public string AUT_USER { get; set; }
		public DateTime? AUT_SYST_CUT_OFF { get; set; }
		public DateTime? AUT_ACQU_CUT_OFF { get; set; }
		public DateTime? AUT_ISSU_CUT_OFF { get; set; }
		public DateTime? AUT_REQU_SYST_TIME { get; set; }
		public DateTime AUT_RESP_SYST_TIME { get; set; }
		public string AUT_AUTH_STAT { get; set; }
		public string AUT_REVE_STAT { get; set; }
		public string AUT_CONF_STAT { get; set; }
		public string AUT_MATC_STAT { get; set; }
		public Int64? AUT_TRAN_TYPE_CODE { get; set; }
		public string AUT_TRAN_CODE { get; set; }
		public Int64? AUT_SYS_CODE { get; set; }
		public Int64? AUT_BIN_CODE { get; set; }

		public string AUT_BIN_TYPE { get; set; }
		public Int64? AUT_PROD_TYPE_CODE { get; set; }

		public Int64? AUT_BIN_IDEN { get; set; }

		public Int64? AUT_ISSU_BANK_CODE { get; set; }

		public Int64? AUT_PROF_MERC_GROU_CODE { get; set; }

		public Int64? AUT_COMM_CODE { get; set; }

		public decimal? AUT_COMM_AMOU { get; set; }
		public decimal? AUT_COMM_FIX { get; set; }
		public decimal? AUT_COMM_RATE { get; set; }
		public decimal? AUT_COMM_MIN { get; set; }
		public decimal? AUT_COMM_MAX { get; set; }
		public Int64? AUT_CARD_STAT { get; set; }

		public Int64? AUT_ACC_STAT { get; set; }

		public Int64? AUT_CUST_STAT { get; set; }
		public Int64? AUT_MCC_GRP_CODE { get; set; }
		public int? AUT_CARD_VIP_LEVE { get; set; }
		public Int64? AUT_SOLV_LEVE_CODE { get; set; }
		public string AUT_MERC_DOM { get; set; }
		public string AUT_PAYM_CHAN { get; set; }
		public Int64? AUT_TERM_STAT { get; set; }
		public Int64? AUT_ACQ_BANK_CODE { get; set; }
		public Int64? AUT_MERC_STAT { get; set; }
		public Int64? AUT_MERC_SOLV { get; set; }
		public int? AUT_ACTI_CTRL { get; set; }
		public int? AUT_AVAI_CTRL { get; set; }
		public int? AUT_BALA_CTRL { get; set; }
		public int? AUT_MERC_ACTI_CTRL { get; set; }
		public string AUT_MTI_CODE { get; set; }
		public int? AUT_ATY_CODE { get; set; }
		public string AUT_PRIM_ACCT_NUMB_F002 { get; set; }
		public string AUT_PROC_CODE_F003 { get; set; }
		public string AUT_TRAN_TYPE_F003_01 { get; set; }
		public string AUT_ACCT_TYPE_FROM_F003_02 { get; set; }
		public string AUT_ACCT_TYPE_TO_F003_03 { get; set; }
		public decimal? AUT_TRAN_AMOU_F004 { get; set; }
		public decimal? AUT_SETT_AMOU_F005 { get; set; }
		public decimal? AUT_BILL_AMOU_F006 { get; set; }
		public decimal? AUT_ACQU_SETT_AMOU { get; set; }
		public decimal? AUT_ISSU_SETT_AMOU { get; set; }
		public DateTime? AUT_TRAN_DATE_TIME_F007 { get; set; }
		public decimal? AUT_BILL_AMOU_FEES_F008 { get; set; }
		public decimal? AUT_SETT_CONV_RATE_F009 { get; set; }
		public decimal? AUT_ACQU_SETT_CONV_RATE { get; set; }
		public decimal? AUT_ISSU_SETT_CONV_RATE { get; set; }
		public decimal? AUT_BILL_CONV_RATE_F010 { get; set; }
		public string AUT_SYST_TRAC_AUDIT_NUMB_F011 { get; set; }
		public DateTime? AUT_DATE_TIME_TRAN_F012 { get; set; }
		public string AUT_STAR_DATE_F013 { get; set; }
		public string AUT_EXPI_DATE_F014 { get; set; }
		public string AUT_SETT_DATE_F015 { get; set; }
		public string AUT_CONV_DATE_F016 { get; set; }
		public string AUT_CAPT_DATE_F017 { get; set; }
		public string AUT_MERC_TYPE_F018 { get; set; }
		public string AUT_ACQR_INST_COUN_CODE_F019 { get; set; }
		public string AUT_PAN_INST_COUN_CODE_F020 { get; set; }
		public string AUT_FORW_INST_COUN_F021 { get; set; }
		public string AUT_POS_ENT_MOD_CODE_F022 { get; set; }
		public string AUT_CARD_ENTR_CAPA_F22_01 { get; set; }
		public string AUT_CARD_AUTH_CAPA_F22_02 { get; set; }
		public string AUT_CARD_CAPT_CAPA_F22_03 { get; set; }
		public string AUT_REWR_CAPA_F22_04 { get; set; }
		public string AUT_CARD_PRSN_F22_05 { get; set; }
		public string AUT_PIN_ENTR_CAPA_F22_06 { get; set; }
		public string AUT_OPER_ENVR_F22_07 { get; set; }
		public string AUT_CARD_HLDR_PRSC_F22_08 { get; set; }
		public string AUT_CARD_DATA_INPT_MODE_F22_09 { get; set; }
		public string AUT_CARD_AUTH_MTHD_F22_10 { get; set; }
		public string AUT_CARD_AUTH_ENTY_F22_11 { get; set; }
		public string AUT_CAT_LEVEL_F22_12 { get; set; }
		public string AUT_CARD_SEQU_NUMB_F023 { get; set; }
		public string AUT_FUNC_CODE_F024 { get; set; }
		public string AUT_MESS_REAS_CODE_F025 { get; set; }
		public string AUT_PIN_CAPT_CODE_F026 { get; set; }
		public string AUT_AUTH_LENG_F027 { get; set; }
		public string AUT_TRAN_AMOU_FEE_F028 { get; set; }
		public string AUT_TRAN_AMOU_FEE_F028_1 { get; set; }
		public decimal? AUT_TRAN_AMOU_FEE_F028_2 { get; set; }
		public string AUT_SETT_AMOU_FEE_F029 { get; set; }
		public string AUT_SETT_AMOU_FEE_F029_1 { get; set; }
		public decimal? AUT_SETT_AMOU_FEE_F029_2 { get; set; }
		public string AUT_ORIG_AMOU_F030 { get; set; }
		public decimal? AUT_ORIG_AMOU_F030_01 { get; set; }
		public decimal? AUT_ORIG_AMOU_F030_02 { get; set; }
		public string AUT_ACQR_INST_ID_CODE_F032 { get; set; }
		public string AUT_FORW_INST_ID_CODE_F033 { get; set; }
		public string AUT_RETR_REF_NUMB_F037 { get; set; }
		public string AUT_AUTH_ID_RESP_F038 { get; set; }
		public string AUT_RESP_CODE_F039 { get; set; }
		public string AUT_RESP_CODE_F039_1 { get; set; }
		public string AUT_RESP_CODE_F039_2 { get; set; }
		public string AUT_SERV_CODE_F040 { get; set; }
		public string AUT_CARD_ACCP_TERM_ID_F041 { get; set; }
		public string AUT_CARD_ACCP_ID_CODE_F042 { get; set; }
		public string AUT_CARD_ACCP_NAME_LOC_F043 { get; set; }
		public string AUT_ADD_RESP_DATA_F044 { get; set; }
		public string AUT_MESS_TEXT_F044_01 { get; set; }
		public string AUT_ACQU_RESP_F044_02 { get; set; }
		public string AUT_ISSU_RESP_F044_03 { get; set; }
		public string AUT_ADDI_RESP_F044_04 { get; set; }
		public string AUT_HSM_RESP_F044_05 { get; set; }
		public string AUT_FIEL_NUMB_F044_06 { get; set; }
		public string AUT_ADDI_DATA_F048 { get; set; }
		public string AUT_MESS_F048_01 { get; set; }
		public string AUT_STAN_IN_F048_02 { get; set; }
		public string AUT_PROD_TYPE_F048_03 { get; set; }
		public string AUT_PRIM_ROUT_F048_04 { get; set; }
		public string AUT_SECO_ROUT_F048_04 { get; set; }
		public string AUT_TRAN_CATE_F048_10 { get; set; }
		public string AUT_CERT_NUMB_F048_11 { get; set; }
		public string AUT_ELEC_COMM_CERT_F048_12 { get; set; }
		public string AUT_ELEC_COMM_SECU_F048_13 { get; set; }
		public string AUT_VERI_REQU_F048_14 { get; set; }
		public string AUT_VERI_RESP_F048_15 { get; set; }
		public string AUT_CVV_PRES_INDI_F048_85 { get; set; }
		public string AUT_CVV_RESP_TYPE_F048_86 { get; set; }
		public string AUT_CVV_VALI_F048_16 { get; set; }
		public string AUT_CVV_CHAN_F048_17 { get; set; }
		public string AUT_CVV_TRAC_F048_18 { get; set; }
		public string AUT_CVV2_DATA_F048_19 { get; set; }
		public string AUT_XID_TRAN_ID_F048_09 { get; set; }
		public string AUT_TRAN_HASH_VALU_F048_10 { get; set; }
		public string AUT_TRAN_CURR_F049 { get; set; }
		public string AUT_SETT_CURR_F050 { get; set; }
		public string AUT_BILL_CURR_F051 { get; set; }
		public string AUT_ACQU_SETT_CURR { get; set; }
		public string AUT_ISSU_SETT_CURR { get; set; }
		public string AUT_ADDI_AMOU_F054 { get; set; }
		public string AUT_ADDI_AMOU_F054_ACCO_TYPE1 { get; set; }
		public string AUT_ADDI_AMOU_F054_AMOU_TYPE1 { get; set; }
		public string AUT_ADDI_AMOU_F054_CURR_CODE1 { get; set; }
		public string AUT_ADDI_AMOU_F054_AMOU_SIGN1 { get; set; }
		public decimal? AUT_ADDI_AMOU_F054_AMOU1 { get; set; }
		public string AUT_ADDI_AMOU_F054_ACCO_TYPE2 { get; set; }
		public string AUT_ADDI_AMOU_F054_AMOU_TYPE2 { get; set; }
		public string AUT_ADDI_AMOU_F054_CURR_CODE2 { get; set; }
		public string AUT_ADDI_AMOU_F054_AMOU_SIGN2 { get; set; }
		public decimal? AUT_ADDI_AMOU_F054_AMOU2 { get; set; }
		public string AUT_INTE_CIRC_CARD_F055 { get; set; }
		public string AUT_ICC_APPL_F055_004F { get; set; }
		public string AUT_TRAC_DATA_F055_0057 { get; set; }
		public string AUT_ISSU_SCRI_TEM1_F055_0071 { get; set; }
		public string AUT_ISSU_SCRI_TEM2_F055_0072 { get; set; }
		public string AUT_APPL_INTE_PROF_F055_0082 { get; set; }
		public string AUT_RESE_F055_0082_01 { get; set; }
		public string AUT_OFFL_SDA_F055_0082_02 { get; set; }
		public string AUT_OFFL_DDA_F055_0082_03 { get; set; }
		public string AUT_CARD_VERI_F055_0082_04 { get; set; }
		public string AUT_TERM_RISK_F055_0082_05 { get; set; }
		public string AUT_ISSU_AUTH_F055_0082_06 { get; set; }
		public string AUT_COMB_DDA_F055_0082_07 { get; set; }
		public string AUT_RESE_F055_0082_08 { get; set; }
		public string AUT_DEDI_FILE_NAME_F055_0084 { get; set; }
		public string AUT_ISSU_SCRI_COMM_F055_0086 { get; set; }
		public string AUT_RESP_CODE_F055_008A { get; set; }
		public string AUT_CVM_LIST_F055_008E { get; set; }
		public string AUT_ISSU_AUTH_DATA_F055_0091 { get; set; }
		public string AUT_ARPC_CRYP_F055_0091_01 { get; set; }
		public string AUT_ARPC_RESP_F055_0091_02 { get; set; }
		public string AUT_TERM_VERI_RESU_F055_0095 { get; set; }
		public string AUT_OFFL_AUTH_F055_0095_01 { get; set; }
		public string AUT_SDA_PASS_F055_0095_02 { get; set; }
		public string AUT_CHIP_DATA_F055_0095_03 { get; set; }
		public string AUT_PAN_TERM_F055_0095_04 { get; set; }
		public string AUT_RESE_F055_0095_05 { get; set; }
		public string AUT_CHIP_TERM_F055_0095_06 { get; set; }
		public string AUT_EXPI_APPL_F055_0095_07 { get; set; }
		public string AUT_APPL_ACTI_F055_0095_08 { get; set; }
		public string AUT_SERV_ALLW_F055_0095_09 { get; set; }
		public string AUT_NEW_CARD_F055_0095_10 { get; set; }
		public string AUT_RESE_F055_0095_11 { get; set; }
		public string AUT_CARD_VERI_F055_0095_12 { get; set; }
		public string AUT_UNRE_CVM_F055_0095_13 { get; set; }
		public string AUT_PIN_TRY_F055_0095_14 { get; set; }
		public string AUT_PIN_WORK_F055_0095_15 { get; set; }
		public string AUT_PIN_PRES_F055_0095_16 { get; set; }
		public string AUT_ONLI_PIN_F055_0095_17 { get; set; }
		public string AUT_RESE_F055_0095_18 { get; set; }
		public string AUT_TRAN_LIMI_F055_0095_19 { get; set; }
		public string AUT_LOWE_LIMI_F055_0095_20 { get; set; }
		public string AUT_UPPE_LIMI_F055_0095_21 { get; set; }
		public string AUT_TRAN_RAND_F055_0095_22 { get; set; }
		public string AUT_FORC_TRAN_F055_0095_23 { get; set; }
		public string AUT_RESE_F055_0095_24 { get; set; }
		public string AUT_ISSU_AUTH_F055_0095_25 { get; set; }
		public string AUT_SCRI_BEFO_F055_0095_26 { get; set; }
		public string AUT_SCRI_AFTE_F055_0095_27 { get; set; }
		public string AUT_RESE_F055_0095_28 { get; set; }
		public string AUT_TRAN_DATE_F055_009A { get; set; }
		public string AUT_TRAN_TYPE_F055_009C { get; set; }
		public string AUT_APPL_EXPI_DATE_F055_5F24 { get; set; }
		public string AUT_APPL_STAR_DATE_F055_5F25 { get; set; }
		public string AUT_TRAN_CURR_F055_5F2A { get; set; }
		public string AUT_TRAN_AMOU_F055_9F02 { get; set; }
		public string AUT_CASH_BACK_F055_9F03 { get; set; }
		public string AUT_APPL_IDEN_F055_9F06 { get; set; }
		public string AUT_APPL_USAG_CTRL_F055_9F07 { get; set; }
		public string AUT_TERM_APPL_VERS_F055_9F09 { get; set; }
		public string AUT_ISSU_APPL_DATA_F055_9F10 { get; set; }
		public string AUT_KEY_INDE_F055_9F10_01 { get; set; }
		public string AUT_CRYP_VERS_F055_9F10_02 { get; set; }
		public string AUT_SECO_CRYP_F055_9F10_03 { get; set; }
		public string AUT_FIRS_CRYP_F055_9F10_04 { get; set; }
		public string AUT_ISSU_AUTH_F055_9F10_05 { get; set; }
		public string AUT_PIN_PERF_F055_9F10_06 { get; set; }
		public string AUT_PIN_FAIL_F055_9F10_07 { get; set; }
		public string AUT_UNAB_ONLI_F055_9F10_08 { get; set; }
		public string AUT_LAST_ONLI_F055_9F10_09 { get; set; }
		public string AUT_PIN_LIMI_F055_9F10_10 { get; set; }
		public string AUT_VELO_CHEC_F055_9F10_11 { get; set; }
		public string AUT_NEW_CARD_F055_9F10_12 { get; set; }
		public string AUT_AUTH_FAIL_F055_9F10_13 { get; set; }
		public string AUT_AUTH_PERF_F055_9F10_14 { get; set; }
		public string AUT_PIN_BLOC_F055_9F10_15 { get; set; }
		public string AUT_SDA_F055_9F10_16 { get; set; }
		public string AUT_NUMB_SCRI_F055_9F10_17 { get; set; }
		public string AUT_SCRI_FAIL_F055_9F10_18 { get; set; }
		public string AUT_RESE_F055_9F10_19 { get; set; }
		public string AUT_IAC_DEFA_F055_9F0D { get; set; }
		public string AUT_IAC_DENI_F055_9F0E { get; set; }
		public string AUT_IAC_ONLI_F055_9F0F { get; set; }
		public string AUT_TERM_COUN_CODE_F055_9F1A { get; set; }
		public string AUT_INTE_DEVI_SERI_F055_9F1E { get; set; }
		public string AUT_APPL_CRYP_F055_9F26 { get; set; }
		public string AUT_CRYP_INFO_DATA_F055_9F27 { get; set; }
		public string AUT_TERM_CAPA_F055_9F33 { get; set; }
		public string AUT_MANU_KEY_F055_9F33_01 { get; set; }
		public string AUT_MAGN_STRI_F055_9F33_02 { get; set; }
		public string AUT_CHIP_READ_F055_9F33_03 { get; set; }
		public string AUT_RESE_F055_9F33_04 { get; set; }
		public string AUT_OFFL_PIN_F055_9F33_05 { get; set; }
		public string AUT_ONLI_PIN_F055_9F33_06 { get; set; }
		public string AUT_SIGN_ALLW_F055_9F33_07 { get; set; }
		public string AUT_RESE_F055_9F33_08 { get; set; }
		public string AUT_SDA_SUPP_F055_9F33_09 { get; set; }
		public string AUT_RESE_F055_9F33_10 { get; set; }
		public string AUT_CARD_CAPT_F055_9F33_11 { get; set; }
		public string AUT_RESE_F055_9F33_12 { get; set; }
		public string AUT_CHLD_VERI_RESU_F055_9F34 { get; set; }
		public string AUT_TERM_TYPE_F055_9F35 { get; set; }
		public string AUT_APPL_TRAN_COUN_F055_9F36 { get; set; }
		public string AUT_UNPR_NUMB_F055_9F37 { get; set; }
		public string AUT_TRAN_SEQU_NUMB_F055_9F41 { get; set; }
		public string AUT_TRAN_CATE_CODE_F055_9F53 { get; set; }
		public string AUT_ICC_PROC_F055_DF80 { get; set; }
		public string AUT_APPL_TYPE_F055_DF81 { get; set; }
		public string AUT_APPL_VERI_F055_DF70 { get; set; }
		public string AUT_CALC_DATA_F055_DF71 { get; set; }
		public string AUT_ACCP_CERT_F055_FF72 { get; set; }
		public string AUT_APPL_TYPE_F055_FF73 { get; set; }
		public string AUT_CARD_APPL_CURR_F055_FF74 { get; set; }
		public string AUT_ISSU_CAI_F055_FF75 { get; set; }
		public string AUT_ISSU_INTE_DATA_F055_FF76 { get; set; }
		public string AUT_ACQU_CAI_F055_FF77 { get; set; }
		public string AUT_AQUI_DATA_F055_FF78 { get; set; }
		public string AUT_ISSU_SCRI_F055_FF00 { get; set; }
		public string AUT_ORIG_DATA_F056 { get; set; }
		public string AUT_MESS_TYPE_F056_01 { get; set; }
		public string AUT_ORIG_TRAC_AUDI_F056_02 { get; set; }
		public DateTime? AUT_ORIG_DATE_TIME_F056_03 { get; set; }
		public string AUT_ORIG_ACQU_ID_F056_04 { get; set; }
		public string AUT_ORIG_FORW_ID_F056_05 { get; set; }
		public string AUT_CPS_DATA_F062 { get; set; }
		public string AUT_AUTH_CHAR_INDI_F062_01 { get; set; }
		public string AUT_TRAN_IDEN_F062_02 { get; set; }
		public string AUT_VALI_CODE_F062_03 { get; set; }
		public string AUT_NETW_DATA_F063 { get; set; }
		public string AUT_BANK_NET_DATA_F063_01 { get; set; }
		public string AUT_NETW_ID_F063_02 { get; set; }
		public string AUT_MESS_REAS_F063_03 { get; set; }
		public string AUT_STIP_SWIT_F063_04 { get; set; }
		public string AUT_RECE_INST_COUN_F068 { get; set; }
		public string AUT_SETT_INST_COUN_F069 { get; set; }
		public string AUT_SETT_INST_ID_CODE_F099 { get; set; }
		public string AUT_RECE_INST_ID_CODE_F100 { get; set; }
		public string AUT_ACCO_ID1_F102 { get; set; }
		public string AUT_ACCO_ID2_F103 { get; set; }
		public string AUT_VALI_STAT { get; set; }
		public string AUT_NOT_MATC_PROC_STAT { get; set; }
		public string AUT_UPDA_ACCO { get; set; }
		public string AUT_UPDA_CARD { get; set; }
		public string AUT_VMT_BUSINESS_APP_ID { get; set; }
		public string AUT_VMT_SENDER_REF_NUMB { get; set; }
		public string AUT_VMT_SENDER_ACC_NUMB { get; set; }
		public string AUT_VMT_SENDER_NAME { get; set; }
		public string AUT_VMT_SENDER_ADDRESS { get; set; }
		public string AUT_VMT_SENDER_CITY { get; set; }
		public string AUT_VMT_SENDER_STATE_PROV { get; set; }
		public string AUT_VMT_SENDER_COUNTRY { get; set; }
		public string AUT_VMT_FUNDS_SOURCE { get; set; }
		public string AUT_VMT_ADTNL_SENDER_DATA { get; set; }
		public Boolean ExistInClearing { get; set; }
	}
}
